name: Pre-commit on feature branches

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Send Slack notification on failure
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: ":x: *Pre-commit 실패 `${{ github.ref_name }}`*"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "*❌ Pre-commit failed on branch `${{ github.ref_name }}`*"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Commit by:*\n<https://github.com/${{ github.actor }}|${{ github.actor }}>"
                  - type: mrkdwn
                    text: "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}"
                  - type: mrkdwn
                    text: "*Actions Run:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"

