name: Terraform Manual Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "삭제할 환경 (dev, main, prod)"
        required: true
        default: "dev"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ap-northeast-2
      S3_BUCKET: my-terraform-logs
      TF_DIR: ./${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/finguard-terraform-admin
          role-session-name: GitHubTerraformDestroy

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_DIR }} init

      - name: Terraform Destroy
        id: destroy
        run: |
          terraform -chdir=${{ env.TF_DIR }} destroy -auto-approve -no-color > destroy.txt

      - name: Upload Destroy Log to S3 and Presign URL
        id: upload_destroy
        run: |
          REPO=${GITHUB_REPOSITORY##*/}
          TS=$(date +%Y%m%d-%H%M%S)
          ENV=${{ github.event.inputs.environment }}
          FILE_NAME="destroy-${REPO}-${TS}-${ENV}.txt"
          aws s3api put-object \
            --bucket ${{ secrets.S3_PLAN_BUCKET }} \
            --key "$FILE_NAME" \
            --body destroy.txt
          URL=$(aws s3 presign s3://${{ secrets.S3_PLAN_BUCKET }}/$FILE_NAME --expires-in 3600)
          echo "$URL" > destroy_url.txt

      - name: Send Slack Message (Destroy)
        run: |
          URL=$(cat destroy_url.txt)
          MSG="⚠️ *Terraform Destroy (${{ github.event.inputs.environment }}) complete*\n🔗 $URL"
          PAYLOAD=$(jq -n --arg text "$MSG" '{text: $text}')
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack notification on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"*❌ Terraform Destroy Workflow Failed (${GITHUB_REF_NAME})*\",
            \"blocks\": [
              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"*Destroy 실패 in <https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|this workflow>*\"
                }
              },
              {
                \"type\": \"section\",
                \"fields\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Actor:*\n<https://github.com/${GITHUB_ACTOR}|${GITHUB_ACTOR}>\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Commit:*\n<https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}|${GITHUB_SHA}>\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Environment:*\n${{ github.event.inputs.environment }}\"
                  }
                ]
              }
            ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
